### ISSUE TITLE
Leaflet map not loading due to an unauthorized situation.

### ISSUE THREAD

**Issue by YaronMiro** [Gizra/elm-hedley#125]
I saw it `locally` and  check the [Live](http://gizra.github.io/elm-hedley/#!/events)  site - both share the same problem.
There is an error coming from the ` https://api.tiles.mapbox.com/v4`
The request for the map data is not valid (unauthorized) and maybe that's why we are unable to get the data and display the map accordingly. 

![selection_263](https://cloud.githubusercontent.com/assets/3907724/12744777/c4e94576-c99e-11e5-9afa-c7e0dfcfa887.png)

**Comment by amitaibu** [comment]
Thanks, I've changed the mapbox access token
