### ISSUE TITLE
BackendConfig usage

### ISSUE THREAD

**Issue by tolgap** [Gizra/elm-hedley#138]
Hi Amitai,

I hope you're doing great. I've been delving into Elm lately and have been using your work on Elm Hedley as an amazing starting point. I really appreciate you keeping it open source so we can learn from it!

I have a question though. You have a notion of "Backends" in your application Config type aliases. How do you determine whether you use the productionURL or the developmentURL? I'm facing this similar challenge, and can't quite pinpoint how you've solved this.

Thank you very much for your time,
Tolga Paksoy.

PS: we had talked in e-mail and you recommended me opening an issue

**Comment by amitaibu** [comment]
Geting the right backend is happening [here](https://github.com/Gizra/elm-hedley/blob/master/src/elm/Config/Update.elm#L35-L51). It's a naive approach - looking at the URL, and finding the right backend from the [backend list](https://github.com/Gizra/elm-hedley/blob/master/src/elm/Config.elm#L22-L26)
