### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by YetAnotherMinion** [Gizra/elm-hedley#150]
Legal won't let us physically look at any github repository that does not have a permissive license (corporate proxy filters out anything `github.com/%name/%project/tree/*` ). This application looks really nice from the front page of elm-lang.org and I would appreciate the opportunity to learn from the code how everything works. I hope it is possible to have a permissive license for this repository.

**Comment by amitaibu** [comment]
Sure. Can you please create a PR to add MIT license to it?
