### ISSUE TITLE
Add footer for anon/auth users

### ISSUE THREAD

**Issue by amitaibu** [Gizra/elm-hedley#42]
`With ♥ from gizra`

**Comment by nader77** [comment]
@amitaibu Please give me write access to this repo, Thanks.

**Comment by amitaibu** [comment]
Until I'm back you can simply fork it.

**Comment by amitaibu** [comment]
I'm taking this one, as we need it before we publish a blog post about it.

**Comment by nader77** [comment]
Sorry, Still learning ELM.

**Comment by amitaibu** [comment]
no worries.

**Comment by amitaibu** [comment]
deployed.
